services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/managmentapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ittimetovenom53
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
     - ./frontend/dist:/usr/share/nginx/html
     - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_DB=managmentapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ittimetovenom53
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network  # Явное указание имени сети
    driver: bridge